### ISSUE TITLE
! LaTeX Error: File `IEEEtran.cls' not found.

### ISSUE THREAD

**Issue by abhisheksoni27** [stsewd/ieee-pandoc-template#1]
```
! LaTeX Error: File `IEEEtran.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.2 \usepackage

pandoc: Error producing PDF
makefile:16: recipe for target 'pdf' failed
make: *** [pdf] Error 43
```

**Comment by abhisheksoni27** [comment]
Adding the file does the trick. Can you include it in the repo? Or Are there copyright issues?

**Comment by stsewd** [comment]
What tool are you using for compile to Latex? I have no problem when running on a full Texlive installation.

I have no idea about the copyright of that file, but I think that would be no problem at all.

**Comment by stsewd** [comment]
On the next week I'll be looking for more information about this issue, but feel free to send a pull request.

**Comment by abhisheksoni27** [comment]
I am using **pandoc**. Right, it does work after I include the file. I'll send a PR. :+1:

**Comment by stsewd** [comment]
@abhisheksoni27 I tested it on Ubuntu 16.4 and Fedora 26, I could not replicate the problem.
What operating system are you using?.

If you are on Ubuntu try: `sudo apt install texlive-full` or on Fedora `sudo dnf install textlive-scheme-full`

**Comment by abhisheksoni27** [comment]
Are you sure installing texlive-full will automatically include the
IEEETran.cls file?

**Comment by stsewd** [comment]
I think so, I tested it on a fresh installation and also I added travis-ci integration to the repo. Let me know if the problem is gone after that.

**Comment by fin-ger** [comment]
Just wanted to note that the file is included in the `texlive-publishers` package. For any future reader :wink:
