### ISSUE TITLE
Incorrect Variable Name

### ISSUE THREAD

**Issue by danielbarry** [stsewd/ieee-pandoc-template#6]
https://github.com/stsewd/ieee-pandoc-template/blob/7d42758e69e2258b99cb8a805776db05d76cea49/metadata.yaml#L5

`affilation` -> `affiliation`

Name to be spelt as specified in the template: https://github.com/stsewd/ieee-pandoc-template/blob/7d42758e69e2258b99cb8a805776db05d76cea49/template.latex#L218

**Comment by stsewd** [comment]
Fixed in https://github.com/stsewd/ieee-pandoc-template/pull/7
